---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jt-capstone-deployment
  namespace: default
  labels:
    app: jt-capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jt-capstone
  template:
    metadata:
      name: jt-capstone-main
      labels:
        app: jt-capstone
    spec:
      containers:
        - name: jt-capstone
          image: tannedlamb/capstone:$BUILD_NUMBER
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jt-capstone-service
  namespace: default
spec:
  selector:
    app: jt-capstone
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
